apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color-homolog
  namespace: dev-argo-cd
spec:
  destination:
    namespace: web-color-homolog
    server: https://kubernetes.default.svc
  project: default
  source:
    path: homolog
    repoURL: https://github.com/edersonbuss/k8s-web-color-page.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color-prod
  namespace: dev-argo-cd
spec:
  destination:
    namespace: web-color-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prod
    repoURL: https://github.com/edersonbuss/k8s-web-color-page.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
 