apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: service-order-events
  namespace: ingestion
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3
  replicas: 1
    

    
